volumes:
  bot_data:
    external: true
    name: ./bot_data

services:
  bot:
    image: novahfly/khinsider_bot:latest
    env_file: .env
    ports:
      - 8010:80
    volumes:
      - ./bot_data:/bot_data
