[tool.poetry]
name = "khinsider_bot"
version = "0.2.1"
description = "Telegram bot to download soundtracks"
authors = ["NovaHFly <mugiviska@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
khinsider-downloader = { git = "https://github.com/NovaHFly/khinsider_downloader" }
starlette = "^0.46.2"
uvicorn = "^0.34.2"
aiogram = "^3.20.0.post0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
