name: Build image
on: [workflow_dispatch, workflow_call]

jobs:

  build_and_push_image_to_dockerhub:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push latest image to dockerHub
        uses: docker/build-push-action@v4
        with:
          context: '.'
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/khinsider_bot:latest
