name: Build image
on: [workflow_dispatch, workflow_call]

jobs:

  get_project_version:
    runs-on: ubuntu-latest

    outputs:
      project_version: ${{ steps.parse_version.outputs.project_version }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Parse version
        id: parse_version
        run: |
          echo "project_version=`grep -oP 'version = "\K([0-9]+\.[0-9]+\.[0-9]+)' pyproject.toml`" >> "$GITHUB_OUTPUT"

  build_and_push_image_to_dockerhub:
    runs-on: ubuntu-latest
    if: |
      github.ref == 'refs/heads/main'

    needs:
      - get_project_version

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push latest image to dockerHub
        uses: docker/build-push-action@v4
        with:
          context: '.'
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/khinsider_bot:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/khinsider_bot:${{needs.get_project_version.outputs.project_version}}  
